[project]
name = "grphx"
version = "0.1.0"
description = "A generic graph data-structure library for Python 3.12+"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
